
export const CANCEL_APP = 'RPT_CANCEL_APP';

export const INIT = 'RPT_INIT';
export const INIT_NO_STATE = 'INIT_NO_STATE';

export const SET_SET_PRODUCTS_CATEGORY_STYLE = 'RPT_SET_PRODUCTS_CATEGORY_STYLE';

export const SET_PROGRESS_BTN = 'RPT_SET_PROGRESS_BTN';

export const SET_POSTATUS_REPORT_PDF = 'RPT_SET_POSTATUS_REPORT_PDF';
export const SET_POSTATUS_REPORT_DONE = 'RPT_SET_POSTATUS_REPORT_DONE';
export const SET_POSTATUS_REPORT_FAILED = 'RPT_SET_POSTATUS_REPORT_FAILED';

export const SET_REASON = 'RPT_SET_REASON';
export const SET_STATE = 'RPT_SET_STATE';
export const SET_STATUS = 'RPT_SET_STATUS';

export const TOGGLE_OPEN_PO_SELECTED = 'RPT_TOGGLE_OPEN_PO_SELECTED';
export const TOGGLE_OPEN_PO_VISIBLE = 'RPT_TOGGLE_OPEN_PO_VISIBLE';

